experiment:
    project_name: scene-graph
    exp_name: dinov2-base-run5
    max_train_examples: 10000000 # not used
    save_every: 1000
    eval_every: 500
    sample_every: 10000000 # not used
    log_every: 500
    log_level: info
    resume_path_from_checkpoint: null


model:
    name: facebook/dinov2-base
    dim : 768
     # give the dimension of the model
    freeze : True
    num_classes : 100
    
    # used only for vit
    patch_size : 32 
    n_heads : 12        
    depth : 12
    mlp_dim : 3072

    top_k_instances : 512
    top_k_relationships : 2



dataset:
    name: vrd
    params:
        root_path:   /home/pranoy/Downloads/vrd
        num_workers: 4
        pin_memory: True
        batch_size: 8
        persistent_workers: True
        shuffle : True
    preprocessing:
        resolution: 518
        center_crop: False
        random_flip: True
        random_crop: True
        mean : null
        std : null
        scale : 1.0

optimizer:
    name: adamw
    params: 
        learning_rate: 5e-5
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    name: cosine_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 1000
        decay_steps: null

loss_weight:
    ce : 1
    bbox : 5
    giou : 2
    scores : 1


training:
    gradient_accumulation_steps: 2
    mixed_precision: "no"
    seed: 42
    num_epochs: 1000
    max_grad_norm: 1.0
