wandb_version: 1

_content:
  desc: null
  value:
    config: cfg/vrd.yaml
    dataset: '{''name'': ''vrd'', ''params'': {''root_path'': ''/home/pranoy/Downloads/vrd'',
      ''num_workers'': 4, ''pin_memory'': True, ''batch_size'': 8, ''persistent_workers'':
      True, ''shuffle'': True}, ''preprocessing'': {''resolution'': 256, ''center_crop'':
      False, ''random_flip'': True, ''random_crop'': True, ''mean'': None, ''std'':
      None, ''scale'': 1.0}}'
    experiment: '{''project_name'': ''scene-graph'', ''exp_name'': ''run1'', ''max_train_examples'':
      10000000, ''save_every'': 1000, ''eval_every'': 500, ''sample_every'': 10000000,
      ''log_every'': 500, ''log_level'': ''info'', ''resume_path_from_checkpoint'':
      None}'
    lr_scheduler: '{''name'': ''cosine_with_warmup'', ''params'': {''learning_rate'':
      ''${optimizer.params.learning_rate}'', ''warmup_steps'': 4000, ''decay_steps'':
      None}}'
    model: '{''name'': ''scene-graph'', ''dim'': 768, ''image_size'': 256, ''patch_size'':
      32, ''n_heads'': 16, ''depth'': 12, ''mlp_dim'': 2048, ''num_classes'': 100}'
    optimizer: '{''name'': ''adam'', ''params'': {''learning_rate'': 0.0001, ''beta1'':
      0.9, ''beta2'': 0.96, ''weight_decay'': 0.0, ''epsilon'': 1e-08}}'
    training: '{''gradient_accumulation_steps'': 32, ''mixed_precision'': ''no'',
      ''seed'': 42, ''num_epochs'': 200, ''max_grad_norm'': None}'
_flags_cache:
  desc: null
  value:
    struct: null
_metadata:
  desc: null
  value: ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True,
    key=None, flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>,
    {}), key_type=typing.Any, element_type=typing.Any)
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1732699957
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 16
      4: 3.10.12
      5: 0.12.21
      6: 4.37.2
      8:
      - 5
